# Generated by Django 3.0 on 2020-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
